export default [
  {
    regionCode: 'MOS,MOW',
    name: 'Москва и область',
    isPopular: true,
    siteId: 'siteMSK',
  },
  {
    regionCode: 'LEN,SPE',
    name: 'Санкт-Петербург и Ленинградская область',
    isPopular: true,
    siteId: 'siteSPB',
  },
  {
    regionCode: 'CHE',
    name: 'Челябинская область',
    isPopular: true,
    siteId: 'siteCHELYABINSK',
  },
  {
    regionCode: 'ROS',
    name: 'Ростовская область',
    isPopular: true,
    siteId: 'siteROSTOV',
  },
  {
    regionCode: 'IRK',
    name: 'Иркутская область',
    isPopular: true,
    siteId: 'siteIRKUTSK',
  },
  {
    regionCode: 'SVE',
    name: 'Свердловская область',
    isPopular: true,
    siteId: 'siteEKT',
  },
  {
    regionCode: 'NIZ',
    name: 'Нижегородская область',
    isPopular: true,
    siteId: 'siteNNOV',
  },
  {
    regionCode: 'PNZ',
    name: 'Пензенская область',
    isPopular: false,
    siteId: 'sitePENZA',
  },
  {
    regionCode: 'PER',
    name: 'Пермский край',
    isPopular: false,
    siteId: 'sitePERM',
  },
  {
    regionCode: 'ORE',
    name: 'Оренбургская область',
    isPopular: false,
    siteId: 'siteORENBURG',
  },
  {
    regionCode: 'ORL',
    name: 'Орловская область',
    isPopular: false,
    siteId: 'siteOREL',
  },
  {
    regionCode: 'YAN',
    name: 'Ямало-Ненецкий АО',
    isPopular: false,
    siteId: 'siteYANAO',
  },
  {
    regionCode: 'PSK',
    name: 'Псковская область',
    isPopular: false,
    siteId: 'sitePSKOV',
  },
  {
    regionCode: 'AL',
    name: 'Республика Алтай',
    isPopular: false,
    siteId: 'SiteALTAI',
  },
  {
    regionCode: 'YAR',
    name: 'Ярославская область',
    isPopular: false,
    siteId: 'siteYAR',
  },
  {
    regionCode: 'PRI',
    name: 'Приморский край',
    isPopular: false,
    siteId: 'siteVLADIVOSTOK',
  },
  {
    regionCode: 'AL',
    name: 'Алтайский край',
    isPopular: false,
    siteId: 'siteBARNAUL',
  },
  {
    regionCode: 'BU',
    name: 'Республика Бурятия',
    isPopular: false,
    siteId: 'siteBURYATIA',
  },
  {
    regionCode: 'BEL',
    name: 'Белгородская область',
    isPopular: false,
    siteId: 'siteBELGOROD',
  },
  {
    regionCode: 'KO',
    name: 'Республика Коми',
    isPopular: false,
    siteId: 'siteKOMI',
  },
  {
    regionCode: 'BRY',
    name: 'Брянская область',
    isPopular: false,
    siteId: 'siteBRYANSK',
  },
  {
    regionCode: 'ARK',
    name: 'Архангельская область',
    isPopular: false,
    siteId: 'siteARH',
  },
  {
    regionCode: 'siteKARELIA',
    name: 'Республика Карелия',
    isPopular: false,
    siteId: 'siteKARELIA',
  },
  {
    regionCode: 'VLG',
    name: 'Вологодская область',
    isPopular: false,
    siteId: 'siteVOLOGDA',
  },
  {
    regionCode: 'VLA',
    name: 'Владимирская область',
    isPopular: false,
    siteId: 'siteVLADIMIR',
  },
  {
    regionCode: 'VGG',
    name: 'Волгоградская область',
    isPopular: false,
    siteId: 'siteVOLGOGRAD',
  },
  {
    regionCode: 'KYA',
    name: 'Красноярский край (Норильск)',
    isPopular: false,
    siteId: 'siteNORILSK',
  },
  {
    regionCode: 'MO',
    name: 'Республика Мордовия',
    isPopular: false,
    siteId: 'siteMORDOVIA',
  },
  {
    regionCode: 'ME',
    name: 'Республика Марий Эл',
    isPopular: false,
    siteId: 'siteMARIEL',
  },
  {
    regionCode: 'TY,KK',
    name: 'Республика Хакасия и Республика Тыва',
    isPopular: false,
    siteId: 'siteKHAKASIA',
  },
  {
    regionCode: 'IVA',
    name: 'Ивановская область',
    isPopular: false,
    siteId: 'siteIVANOVO',
  },
  {
    regionCode: 'VOR',
    name: 'Воронежская область',
    isPopular: false,
    siteId: 'siteVORONEZH',
  },
  {
    regionCode: 'TA',
    name: 'Республика Татарстан',
    isPopular: false,
    siteId: 'siteKAZAN',
  },
  {
    regionCode: 'YEV',
    name: 'Еврейская АО',
    isPopular: false,
    siteId: 'siteEAO',
  },
  {
    regionCode: 'KGD',
    name: 'Калининградская область',
    isPopular: false,
    siteId: 'siteKALININGRAD',
  },
  {
    regionCode: 'KLU',
    name: 'Калужская область',
    isPopular: false,
    siteId: 'siteKALUGA',
  },
  {
    regionCode: 'RYA',
    name: 'Рязанская область',
    isPopular: false,
    siteId: 'siteRYAZAN',
  },
  {
    regionCode: 'KAM',
    name: 'Камчатский край',
    isPopular: false,
    siteId: 'siteKAMCHATKA',
  },
  {
    regionCode: 'SAM',
    name: 'Самарская область',
    isPopular: false,
    siteId: 'siteSAMARA',
  },
  {
    regionCode: 'KEM',
    name: 'Кемеровская область',
    isPopular: false,
    siteId: 'siteKUZBASS',
  },
  {
    regionCode: 'SAR',
    name: 'Саратовская область',
    isPopular: false,
    siteId: 'siteSARATOV',
  },
  {
    regionCode: 'SAK',
    name: 'Сахалинская область',
    isPopular: false,
    siteId: 'siteSAKHALIN',
  },
  {
    regionCode: 'KDA,AD',
    name: 'Краснодарский край и Республика Адыгея',
    isPopular: false,
    siteId: 'siteKRASNODAR',
  },
  {
    regionCode: 'KYA',
    name: 'Красноярский край (кроме Норильска)',
    isPopular: false,
    siteId: 'siteKRASNOYARSK',
  },
  {
    regionCode: 'TAM',
    name: 'Тамбовская область',
    isPopular: false,
    siteId: 'siteTAMBOV',
  },
  {
    regionCode: 'SMO',
    name: 'Смоленская область',
    isPopular: false,
    siteId: 'siteSMOLENSK',
  },
  {
    regionCode: 'KIR',
    name: 'Кировская область',
    isPopular: false,
    siteId: 'siteKIROV',
  },
  {
    regionCode: 'KOS',
    name: 'Костромская область',
    isPopular: false,
    siteId: 'siteKOSTROMA',
  },
  {
    regionCode: 'LIP',
    name: 'Липецкая область',
    isPopular: false,
    siteId: 'siteLIPETSK',
  },
  {
    regionCode: 'MAG',
    name: 'Магаданская область',
    isPopular: false,
    siteId: 'siteMAGADAN',
  },
  {
    regionCode: 'TVE',
    name: 'Тверская область',
    isPopular: false,
    siteId: 'siteTVER',
  },
  {
    regionCode: 'KGN',
    name: 'Курганская область',
    isPopular: false,
    siteId: 'siteKURGAN',
  },
  {
    regionCode: 'KRS',
    name: 'Курская область',
    isPopular: false,
    siteId: 'siteKURSK',
  },
  {
    regionCode: 'TOM',
    name: 'Томская область',
    isPopular: false,
    siteId: 'siteTOMSK',
  },
  {
    regionCode: 'TUL',
    name: 'Тульская область',
    isPopular: false,
    siteId: 'siteTULA',
  },
  {
    regionCode: 'MUR',
    name: 'Мурманская область',
    isPopular: false,
    siteId: 'siteMURMANSK',
  },
  {
    regionCode: 'ULY',
    name: 'Ульяновская область',
    isPopular: false,
    siteId: 'siteULN',
  },
  {
    regionCode: 'TYU',
    name: 'Тюменская область',
    isPopular: false,
    siteId: 'siteTYUMEN',
  },
  {
    regionCode: 'UD',
    name: 'Удмуртская Республика',
    isPopular: false,
    siteId: 'siteIZHEVSK',
  },
  {
    regionCode: 'NVS',
    name: 'Новосибирская область',
    isPopular: false,
    siteId: 'siteNOVOSIBIRSK',
  },
  {
    regionCode: 'CU',
    name: 'Чувашская Республика',
    isPopular: false,
    siteId: 'siteCHUVASHIA',
  },
  {
    regionCode: 'OMS',
    name: 'Омская область',
    isPopular: false,
    siteId: 'siteOMSK',
  },
  {
    regionCode: 'KHM',
    name: 'Ханты-Мансийский АО—Югра',
    isPopular: false,
    siteId: 'siteHMAO',
  },
  {
    regionCode: 'NGR',
    name: 'Новгородская область',
    isPopular: false,
    siteId: 'siteNOVGOROD',
  },
  {
    regionCode: 'KHA',
    name: 'Хабаровский край',
    isPopular: false,
    siteId: 'siteKHABAROVSK',
  },
];
